[VGNWB-212] fixed first character not triggering create button
diging/vogon-web pull request #118
Opened 2017-08-25 18:02 UTC by tjquinn1

When the first character is selected, this.position.startOffset = 0 which evaluates to false causing the ready function to fail. The else clause is needed because without it the range selection states true-5 instead of 0-5

2017-08-25 19:21 UTC, jdamerow requested changes

2017-08-25 19:21 UTC, jdamerow commented on annotations/static/annotations/js/annotators/text.js
> +                startPos = true;
why do you first set the value to the offset and then set it to true?

2017-08-25 19:21 UTC, jdamerow commented on annotations/static/annotations/js/annotators/text.js
> -            return (this.position.startOffset && this.position.endOffset && this.position.representation.trim().length > 0 && this.text.id && this.user.id && this.concept);
and `this.position.startOffset >= 0` didn't work?

2017-08-25 19:21 UTC, jdamerow commented on annotations/static/annotations/js/annotators/text.js
> +            return (startPos && this.position.endOffset && this.position.representation.trim().length > 0 && this.text.id && this.user.id && this.concept);
what if startOffset is > 0?

2017-08-25 19:37 UTC, tjquinn1 commented
After double checking the first setting of startPos is not necessary and I
will remove it. Setting  this.position.startOffset >= 0  does not work, it
just evaluates to 0. In javascript 0 evaluates to false and in javascript
when using the and operator the function will stop evaluating after the
first false. And by startOffset > 0 do you mean if the function was written
like this.position.startOffset > 0? If not the function should runs as
normal when the value is greater than 0.

On Fri, Aug 25, 2017 at 12:22 PM, Julia Damerow <notifications@github.com>
wrote:

> Closed #118 <https://github.com/diging/vogon-web/pull/118>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/diging/vogon-web/pull/118#event-1222018704>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AQAPc7n7m1870WuLBZxsPJHsg8zVWruaks5sbx7YgaJpZM4PC_Jc>
> .
>

2017-08-25 19:40 UTC, jdamerow commented
yes, I mean `this.position.startOffset >= 0`. This should not evaluate to 0 but to true or false, which should be fine.

2017-08-25 19:44 UTC, tjquinn1 commented
yep that works like a charm. Should I resubmit the pull request?

On Fri, Aug 25, 2017 at 12:40 PM, Julia Damerow <notifications@github.com>
wrote:

> yes, I mean this.position.startOffset >= 0. This should not evaluate to 0
> but to true or false, which should be fine.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/diging/vogon-web/pull/118#issuecomment-325017428>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AQAPc8EIEQvmJNSle0mnNzF6nFnXOKsRks5sbyMdgaJpZM4PC_Jc>
> .
>

2017-08-30 09:34 UTC, jdamerow approved these changes

2017-08-30 09:35 UTC, merged