Story/vgnwb 219
diging/vogon-web pull request #120
Opened 2017-08-30 20:46 UTC by tjquinn1

Moved concept types to settings to allow them to be configurable when necessary.

2017-08-31 13:24 UTC, jdamerow requested changes

2017-08-31 13:24 UTC, jdamerow commented on vogon/settings.py
> +GEOGRAPHIC = os.environ.get('GEOGRAPHIC', 'dfc95f97-f128-42ae-b54c-ee40333eae8c')
the environment variables should be called something that makes it clear what they are for. 'personal' could be anything.

2017-08-31 20:40 UTC, tjquinn1 commented
Made variable names more verbose

2017-09-01 08:52 UTC, jdamerow requested changes

2017-09-01 08:52 UTC, jdamerow commented on .inputrc
> +TAB: menu-complete
remove this file

2017-09-01 08:52 UTC, jdamerow commented on vogon/settings.py
> +GEOGRAPHIC_CONCEPT_TYPE = os.environ.get('GEOGRAPHIC', 'dfc95f97-f128-42ae-b54c-ee40333eae8c')
the environment variables are still called "PERSONAL", etc.

2017-09-05 21:29 UTC, tjquinn1 commented
Removed .inputrc file and added more verbose environment names

2017-09-06 11:16 UTC, jdamerow approved these changes

2017-09-06 11:17 UTC, merged