Story/vgnwb 366
diging/vogon-web pull request #216
Opened 2021-11-05 21:00 UTC by sudheerad9

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [ ] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [ ] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [ ] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [ ] I am not reformatting any files in the wrong format or without cause. 
- [ ] I am not changing file encoding or line endings to something else than UTF-8, LF
- [ ] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [ ] I have added Javadoc/documentation where appropriate
- [ ] I have added test cases where appropriate
- [ ] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
(you can copy the ticket if it hasn't changed) 

...Put description here...
  
## Anything else the reviewer needs to know?

... describe here ...

2021-11-08 19:43 UTC, sudheerad9 commented on repository/managers/citesphere.py
> +        with open('/home/sudheera/dev/django/vogon-web/repository/managers/data','r') as file:
mock data for testing

2022-03-15 19:44 UTC, tjquinn1 requested changes

2022-03-15 19:44 UTC, tjquinn1 commented on accounts/views.py
> +
remove extra line

2022-03-15 19:44 UTC, tjquinn1 commented on repository/managers/citesphere.py
> +        with open('/home/sudheera/dev/django/vogon-web/repository/managers/data','r') as file:
If your going to include this, it needs to be a relative path or it needs to be env variable. This path will only work on your machine

2022-03-15 19:44 UTC, tjquinn1 commented on repository/managers/citesphere.py
> +        end_point = 'https://diging.asu.edu/geco-giles-staging/api/v2/resources/files'
Make this an env variable. That way if the url changes we only have to change it one place

2022-05-04 23:58 UTC, sudheerad9 commented on annotations/views/citesphere_views.py
> +        result = data[2]
Accessing one of the files, since in vogon we need to display only a single file

2022-05-04 23:59 UTC, sudheerad9 commented on annotations/views/citesphere_views.py
> +        result = data[2]
Accessing single file since vogon only needs one file from citesphere

2023-09-19 17:25 UTC, jdamerow requested changes

2023-09-19 17:25 UTC, jdamerow commented on accounts/views.py
> +				'exp': arrow.utcnow().shift(days=1).timestamp,
I don't think we want the reset tokens to be valid for a whole day, they should be fairly short lived, so maybe 2 or 4 hours?

2023-09-19 17:25 UTC, jdamerow commented on annotations/relations.py
> +        raise InvalidData('Missing fields: %s' % '; '.join(list(remaining)))
should that be `missing`?

2023-09-19 17:25 UTC, jdamerow commented on annotations/relations.py
> +    def update_relation(template_part, data, relationset, cache={}, appellation_cache={}, project_id=None):
Is there a reason this is not defined as a private function outside of this function?

2023-09-19 17:25 UTC, jdamerow commented on annotations/views/amphora_views.py
> +        if target_project.texts.filter(pk=text.pk).exists():
I would check this first, since if this is true, then it doesn't matter if the user owns the project or not.

2023-09-19 17:25 UTC, jdamerow commented on annotations/views/amphora_views.py
> +            target_project.save(force_update=True)
why is `force_update` needed here?

2023-09-19 17:25 UTC, jdamerow commented on annotations/views/utils.py
> +def get_params(request, pk):
get parameter of what?

2023-09-19 17:25 UTC, jdamerow commented on requirements.txt
> +#django-toolbelt==0.0.1
remove if not needed

2023-09-19 17:25 UTC, jdamerow commented on test.log
do not commit

2023-09-19 17:25 UTC, jdamerow commented on vogon/settings.py
> +DEBUG = os.environ.get('DEBUG', 'True')
this should be off by default

2023-09-19 17:25 UTC, jdamerow commented on vogon/settings.py
> +ALLOWED_HOSTS = ["amphora.asu.edu", "localhost", "127.0.0.1", "129.219.40.16"]
this needs to be set via environment varialbe

2023-09-19 17:25 UTC, jdamerow commented on vogon/urls.py
> +      terms_of_service="https://www.google.com/policies/terms/",
we don't want to use Google's terms of services. remove if not required, or otherwise put the DigInG url here.

2023-11-01 23:41 UTC, jophals approved these changes

2023-11-01 23:43 UTC, merged