[VGNWB-370_1] add api to check reset token
diging/vogon-web pull request #222
Opened 2022-02-04 20:30 UTC by sudheerad9

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [ ] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [ ] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [ ] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [ ] I am not reformatting any files in the wrong format or without cause. 
- [ ] I am not changing file encoding or line endings to something else than UTF-8, LF
- [ ] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [ ] I have added Javadoc/documentation where appropriate
- [ ] I have added test cases where appropriate
- [ ] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
(you can copy the ticket if it hasn't changed) 

...Put description here...
  
## Anything else the reviewer needs to know?

... describe here ...

2022-03-15 19:55 UTC, tjquinn1 requested changes

2022-03-15 19:55 UTC, tjquinn1 commented on accounts/views.py
> +		return Response({})
return a status.

2022-03-15 19:55 UTC, tjquinn1 commented on accounts/views.py
> +	return Response({"success": True, "message": "Token exists for the user"})
return a status

2022-03-15 19:57 UTC, tjquinn1 requested changes

2022-03-15 19:57 UTC, tjquinn1 commented on accounts/views.py
> +			return Response({ "success": False, "message": "Reset token not found" }, status=404)
use django rest status's. status=status.HTTP_404_NOT_FOUND. This way the implementation is always standardized.

2022-03-15 19:57 UTC, tjquinn1 commented on accounts/views.py
> +			return Response({ "success": False, "message": "User not found" }, status=404)
use django rest status's. status=status.HTTP_404_NOT_FOUND. This way the implementation is always standardized.

2022-03-18 20:16 UTC, tjquinn1 commented
Do you have a script to trigger all the resets?

2023-05-24 20:56 UTC, jophals approved these changes
Approved

2023-05-24 20:58 UTC, merged